### ISSUE TITLE
[suggestion] some positive enhancements 

### ISSUE THREAD

**Issue by snow-blade** [jobream/List-of-Learning-Resources#2]
We should also add some coding communities as coding isn't just about writing code, as sometimes we need to learn to collaborate with others to boost our knowledge, also we should add some dev-blogs that are useful

**Comment by slimcoders** [comment]
Great decision :)

**Comment by slimcoders** [comment]
@snow-blade plz check i added few communities. Feel free to send PR on that.

**Comment by MRslimcoder** [comment]
@all-contributors please add @MRslimcoder for bug, blog, code, content, doc, review, test, example.
