### ISSUE TITLE
Need to add icons and add descriptions in all resources

### ISSUE THREAD

**Issue by MRslimcoder** [jobream/List-of-Learning-Resources#56]
Hi team, 's we need to do a big change related to icons and descriptions, we are going to update the whole readme.md currently a list of learning resources is not looking good to me anyone interested in collaborating on this issue?

**Comment by MRslimcoder** [comment]
@AvidCoder101 are you interested? can we discuss?

**Comment by AvidCoder101** [comment]
@MRslimcoder Yes, we can discuss here on what to do.

**Comment by MRslimcoder** [comment]
@AvidCoder101 I will share all details on this issue but first check PR #57 we want to do changes something like this one.

**Comment by AvidCoder101** [comment]
I've added my comment, and I like the idea

**Comment by MRslimcoder** [comment]
![Screenshot_20210722-191934](https://user-images.githubusercontent.com/28563357/126655067-ceb38401-5fd9-4284-9b80-e03b2f37eed3.png)

We need to fix this icon it's not looking good to me, do you guys have any other solution? otherwise we can remove it.

**Comment by AvidCoder101** [comment]
@MRslimcoder do you mean by changing the whole icon or how it is formatted?

**Comment by MRslimcoder** [comment]
@AvidCoder101 I mean we can change format little bit or we change move it to middle with jobream text.

**Comment by CodingSpecies** [comment]
We could somehow move the text under the icon, and format it to the center? I tried that , but it didn't work.

**Comment by AvidCoder101** [comment]
I think I know a way to do so. I will make a PR.

**Comment by MRslimcoder** [comment]
![Screenshot_20210722-192610](https://user-images.githubusercontent.com/28563357/126655976-92d0846f-8550-49ae-b7d4-5df1fb3e8367.png)

We also need to show atleast 5 sources to user and then rest on seperate MD file.

**Comment by CodingSpecies** [comment]
Ok, I will do that.

**Comment by CodingSpecies** [comment]
For the logo, is this good?
![image](https://user-images.githubusercontent.com/70807500/126656647-4a2b5215-8228-48ac-bb71-e918f987bc8c.png)

**Comment by MRslimcoder** [comment]
Amazing 🙏

**Comment by AvidCoder101** [comment]
@CodingSpecies could you please make a PR for that logo. It looks good (:

**Comment by MRslimcoder** [comment]
@CodingSpecies @AvidCoder101 I request you both to create a issue that "you want to join this organization I will mention owner and send him a mail".

**Comment by AvidCoder101** [comment]
@MRslimcoder I've made an issue.

**Comment by MRslimcoder** [comment]
@CodingSpecies @AvidCoder101 You both are now promoted to member and I as owner LOL 😂

**Comment by AvidCoder101** [comment]
Thanks @MRslimcoder 😀

**Comment by MRslimcoder** [comment]
@CodingSpecies @AvidCoder101 Welcome to Jobream community ❤️
