### ISSUE TITLE
Need a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by MRslimcoder** [jobream/List-of-Learning-Resources#62]
@CodingSpecies & @AvidCoder101 now we changed whole boilerplate of this repo, we need a CONTRIBUTING.md where we add key points about how newbie can contribute to this project.

**Comment by MRslimcoder** [comment]
I will add a code of conduct file by myself.

**Comment by AvidCoder101** [comment]
Could I use a ready made file that I have?

**Comment by MRslimcoder** [comment]
![Screenshot_20210722-201827](https://user-images.githubusercontent.com/28563357/126664335-2c670781-ac39-402b-8e88-eda9a8c0f06d.png)

In last Git Tutorial section we don't have a description we need to fix this.

**Comment by MRslimcoder** [comment]
> Could I use a ready made file that I have?

Yeah sure but sure it easy to understand for beginners even though that will be ready made but we need to update it according to our need.

**Comment by AvidCoder101** [comment]
I've made a PR for this file
