### ISSUE TITLE
Turn the README.md into a website, using github pages.

### ISSUE THREAD

**Issue by CodingSpecies** [jobream/List-of-Learning-Resources#67]
I could also change the README.md into a website, with a domain, if wanted to.

**Comment by MRslimcoder** [comment]
nice idea, and we can also use js.org with that.

**Comment by MRslimcoder** [comment]
@CodingSpecies @AvidCoder101 https://jobream.github.io/List-of-Learning-Resources/ our website is ready.

**Comment by MRslimcoder** [comment]
I also sent a PR to js.org for domain, if successful our domain will be list-of-learning-resources.js.org

**Comment by MRslimcoder** [comment]
Guy's bad news js.org is not accepting our PR, because they want projects related to JavaScript on while we are only writing blogs and README.md's

**Comment by AvidCoder101** [comment]
Ok, thanks @MRslimcoder
