### ISSUE TITLE
Fork changes description should be in top and not on down.

### ISSUE THREAD

**Issue by MRslimcoder** [jobream/List-of-Learning-Resources#70]
![Screenshot_20210722-210722](https://user-images.githubusercontent.com/28563357/126671825-6677add8-86d7-4db0-baee-3a502b4bcf3f.png)

Also fork changes is on top for sections have seperate READMA.md's

**Comment by MRslimcoder** [comment]
@CodingSpecies

**Comment by MRslimcoder** [comment]
@CodingSpecies we forgot communities section wr need to add fork description to that one as well as.

**Comment by CodingSpecies** [comment]
Done #72

**Comment by MRslimcoder** [comment]
@CodingSpecies can you guide me i want to join your 3 organizations.

**Comment by CodingSpecies** [comment]
@MRslimcoder I just contributed to their repositaries.

**Comment by MRslimcoder** [comment]
> @MRslimcoder I just contributed to their repositaries.

Okay thank you 😃
