### ISSUE TITLE
Section of resources are not looking good 

### ISSUE THREAD

**Issue by MRslimcoder** [jobream/List-of-Learning-Resources#83]
@CodingSpecies @AvidCoder101 see first 2 sections we have software development types (Mobile, Web) and then we have learn python & learn RE.

I was thinking to change sections:

1) Computer Programming: Resources related to all programming languages including books and website.

2) Competitive Programming: Resources related to competitive programming books and website.

3) Software Development: (books+website)
    1. Categories
    - Mobile Development
    - Web Development 
    - Desktop Development
    2. Tools

4)  Other areas: (books+website)
   1. Cloud Computing
    - Resources
    - Tools
    2. DevOps
    - Resources 
    - Tools

5) Communities (Links)

While we are going to remove books sessions as it will be already in above sections.

**Comment by AvidCoder101** [comment]
@MRslimcoder we combine some of the section into another section? Example : put Learn Python into Computer Programming

**Comment by MRslimcoder** [comment]
@AvidCoder101 yes!

**Comment by AvidCoder101** [comment]
I've tried my best to sort this issue our (:
