### ISSUE TITLE
Website not working.

### ISSUE THREAD

**Issue by CodingSpecies** [jobream/List-of-Learning-Resources#92]
The GitHub pages website does not work, it still redirects you to the js.org website.

**Comment by AvidCoder101** [comment]
@CodingSpecies, for me, the Github Pages are working

**Comment by MRslimcoder** [comment]
@CodingSpecies remove cache and try again.

**Comment by MRslimcoder** [comment]
@AvidCoder101 @CodingSpecies we need to solve #83 please check.
